import Curve from "@/components/Layout/Curve";
import Description from "@/components/testing/src/components/Description";
import Projects from "@/components/custom/Projects";
import Head from "next/head";
import Experience from "@/components/custom/Projects/components/experiences";
import Tool from "@/components/custom/Projects/components/tools";
const RoundedText = ({text}) => {
  const svgStyles = {
    width: "100px", // Set the width and height as needed
    height: "100px",
    position: "absolute",
    top: "0px",
    right: "20px",
    padding: "5px",
  };

  const pathStyles = {
    fill: "none",
    // stroke: 'white',
    strokeWidth: "1",
  };

  const textPathStyles = {
    fontSize: "17px",
    fill: "white",
  };

  return (
    <svg
      viewBox="0 0 100 100"
      xmlns="http://www.w3.org/2000/svg"
      style={svgStyles}
      className="madimi"
    >
      <path
        id="circlePath"
        d="
          M 10, 50
          a 40,40 0 1,1 80,0
          40,40 0 1,1 -80,0
        "
        style={pathStyles}
      />
      <text>
        <textPath href="#circlePath" style={textPathStyles} className="">
          {text}
        </textPath>
      </text>
    </svg>
  );
};

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Curve backgroundColor={"#0f172a"}>
        <div className="flex justify-center px-[1rem] rubik">
          <div className="relative z-10 container flex flex-col lg:flex-row gap-12">
            <div className="lg:w-4/12 relative">
              <p className="text-primary absolute -left-2 lg:-left-12 -rotate-45 top-12 madimi">
                Services
              </p>
              <h1 className="text-[3.5rem] md:text-[5rem] ml-[2rem] lg:ml-0 text-primary">
                Services I <br />
                Offer
              </h1>
              <p className="mt-6 text-white major">
                We help ambitious business like you generate more profits by
                building awareness, driving web traffic, connecting with
                customers and growing sales.
              </p>
              <div className="relative h-40">
                <RoundedText text="- services - services - services -"/>
              </div>
            </div>
            <div className=" lg:w-8/12">
              <Projects />
            </div>
          </div>
        </div>

        <div className="flex justify-center madimi mt-20 lg:mt-40">
          <div className="relative z-10 container flex gap-12 flex-col lg:flex-row ">
            <div className="lg:w-4/12 relative">
              {/* <div> */}
                <p className="text-primary absolute -left-2 lg:-left-12 -rotate-45 top-12 madimi">
                  Experience
                </p>
                <h1 className="text-[3.5rem] md:text-[5rem] ml-[2rem] lg:ml-0 text-primary rubik">
                  Job
                  <br />
                  Experience
                </h1>
                <p className="mt-6 text-white major">
                  A specialist in UI/UX design. A passion of mine is designing
                  and solving problems through user experience, primarily on
                  modern UI.
                </p>
              {/* </div> */}
              <div className="relative h-32 lg:h-40">
                <RoundedText text="- experience - experience - experience"/>
              </div>
            </div>
            <div className=" lg:w-8/12">
              <p className="text-white madimi text-4xl mb-8">Experience</p>
              <Experience />
            </div>
          </div>
        </div>

        <div className="flex justify-center madimi mt-20 lg:mt-40 mb-[40rem]">
          <div className="relative z-10 container flex flex-col lg:flex-row gap-12">
            <div className="lg:w-4/12 relative">
              <p className="text-primary absolute -left-2 lg:-left-12 -rotate-45 top-12 madimi">
                Tools
              </p>
              <h1 className="text-[3.5rem] md:text-[5rem] ml-[2rem] lg:ml-0 text-primary rubik">
                Tools I
                <br />
                Use
              </h1>
              <p className="mt-6 text-white major">
                A specialist in UI/UX design. A passion of mine is designing and
                solving problems through user experience, primarily on modern
                UI.
              </p>
              <div className="relative h-40">
                <RoundedText />
              </div>
            </div>
            <div className=" lg:w-8/12">
              <p className="text-white madimi text-4xl mb-8">Experience</p>
              <Tool />
            </div>
          </div>
        </div>
      </Curve>
    </>
  );
}
